// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rryovvfdyrqpqppuymfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyeW92dmZkeXJxcHFwcHV5bWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTMwNTIsImV4cCI6MjA2MDI2OTA1Mn0.XBkrm-D9jrnS4yH9nzlHSwGgDrwGuH-iKjR2f5PpDFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);